# how often the content should be fetched given in seconds
refresh_interval_seconds: <interval in seconds>
# optional - defaut value: 600

# list of watchers containing info on which urls to scrape and to whom the emails should be sent
watchers:
  -
    # name only used for logging purposes
    name: <name of the watcher>

    # urls to scap matching search criteria
    # for example:
    # boliga_url: http://www.boliga.dk/soeg/resultater/a194d60c-e272-4c09-a7fd-899763577c58?sort=liggetid-a
    # dba_url: http://www.dba.dk/boliger/andelsbolig/andelslejligheder/vaerelser-3/?soeg=andelsbolig&vaerelser=4&vaerelser=5&vaerelser=6&boligarealkvm=(70-)&sort=listingdate-desc&pris=(1500000-2499999)&pris=(1000000-1499999)&soegfra=1060&radius=5
    boliga_url: <boliga url search criteria from: http://www.boliga.dk>
    dba_url: <dba url search criteria from: http://www.dba.dk>

    # the address where the emails originate from
    # note - when using gmail from an external app, you need to generate an app-specific password
    # see https://support.google.com/mail/answer/1173270?hl=en
    gmail_sender: <gmail address email>
    gmail_password: <gmail app password generated here: https://security.google.com/settings/security/apppasswords>

    # the list of emails to whom the emails should be sent
    email_recipients:
      - <recipient 1 email address>
      - <recipient 2 email address>

    # whether or not the recipients should be bcc'ed
    should_bcc_recipients: <yes or no>
    # optional - defaut value: no
